package com.werkflow.admin.dto.connector;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
public class ConnectorApiKeyRequest {

    /** Raw key generated by UI (32-byte hex) — stored encrypted, never logged. */
    @NotBlank @Size(max = 200)
    private String rawKey;

    /** SHA-256 hex of rawKey — registered in ERP and used for inbound auth validation. */
    @NotBlank @Pattern(regexp = "[a-fA-F0-9]{64}", message = "keyHash must be a 64-char hex SHA-256 digest")
    private String keyHash;

    @NotBlank @Size(max = 200)
    private String keyName;
}
